name: React CI

on: push

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Install dependencies
        run: pnpm install

      - name: Run Jest tests
        run: pnpm test -- --passWithNoTests
        env:
          CI: false

  e2e:
    runs-on: ubuntu-latest
    env:
      REACT_APP_TOKEN: 8c5996d5-fb89-46c9-8821-7063cfbc18b1
      REACT_APP_WEPAPI: https://app.codescreen.com/api/

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Install dependencies
        run: pnpm install

      - name: Install and run Cypress tests
        uses: cypress-io/github-action@v5

        with:
          start: pnpm run start
          wait-on: "http://localhost:3000"
          browser: chrome
          record: true
          parallel: true # Runs test in parallel using settings above
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
